---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gogs
  namespace: default
  annotations:
    gethomepage.dev/href: "https://gogs.clusterlab.cc"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Self-hosted Git service"
    gethomepage.dev/group: Tools
    gethomepage.dev/icon: gogs.png
    gethomepage.dev/name: Gogs
    gethomepage.dev/pod-selector: "app=gogs"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`gogs.clusterlab.cc`)
      kind: Rule
      services:
        - name: gogs-service
          port: 80
  tls:
    secretName: gogs-tls
