---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gogs-tls
  namespace: default
spec:
  secretName: gogs-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - gogs.clusterlab.cc
