apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: readarr
  namespace: media-services
  annotations:
    gethomepage.dev/href: "http://readarr.clusterlab.cc"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Book and audiobook collection manager for Usenet and BitTorrent users."
    gethomepage.dev/group: Media
    gethomepage.dev/icon: readarr.png
    gethomepage.dev/name: Readarr
    gethomepage.dev/pod-selector: "app=readarr"

spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`readarr.clusterlab.cc`)
      kind: Rule
      services:
        - name: readarr
          port: http
  tls:
    secretName: readarr-clusterlab-cc-tls
