apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: readarr-clusterlab-cc
  namespace: media-services
spec:
  secretName: readarr-clusterlab-cc-tls
  dnsNames:
    - readarr.clusterlab.cc
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
