---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: decypharr
  namespace: media-services
  annotations:
    gethomepage.dev/href: "http://decypharr.clusterlab.cc"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Real-Debrid WebDAV cloud storage mounter"
    gethomepage.dev/group: Download Clients
    gethomepage.dev/icon: mdi-cloud-sync
    gethomepage.dev/name: Decypharr
    gethomepage.dev/pod-selector: "app=decypharr"

spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`decypharr.clusterlab.cc`)
      kind: Rule
      services:
        - name: decypharr
          port: http
  tls:
    secretName: decypharr-clusterlab-cc-tls


---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: radarr-dav
  namespace: media-services
  annotations:
    gethomepage.dev/href: "http://radarr-dav.clusterlab.cc"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Movie collection manager for WebDAV/Debrid users."
    gethomepage.dev/group: Media
    gethomepage.dev/icon: radarr.png
    gethomepage.dev/name: Radarr DAV
    gethomepage.dev/pod-selector: "app=decypharr"

spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`radarr-dav.clusterlab.cc`)
      kind: Rule
      services:
        - name: radarr-dav
          port: http
  tls:
    secretName: radarr-dav-clusterlab-cc-tls


---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sonarr-dav
  namespace: media-services
  annotations:
    gethomepage.dev/href: "http://sonarr-dav.clusterlab.cc"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "TV series collection manager for WebDAV/Debrid users."
    gethomepage.dev/group: Media
    gethomepage.dev/icon: sonarr.png
    gethomepage.dev/name: Sonarr DAV
    gethomepage.dev/pod-selector: "app=decypharr"

spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`sonarr-dav.clusterlab.cc`)
      kind: Rule
      services:
        - name: sonarr-dav
          port: http
  tls:
    secretName: sonarr-dav-clusterlab-cc-tls


---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyfin-dav
  namespace: media-services
  annotations:
    gethomepage.dev/href: "http://streaming.clusterlab.cc"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Media streaming server with WebDAV support"
    gethomepage.dev/group: Media
    gethomepage.dev/icon: jellyfin.png
    gethomepage.dev/name: Jellyfin DAV
    gethomepage.dev/pod-selector: "app=decypharr"

spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`streaming.clusterlab.cc`)
      kind: Rule
      services:
        - name: jellyfin-dav
          port: http
  tls:
    secretName: streaming-clusterlab-cc-tls
