---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media-services

resources:
- deployment.yml
- service.yml
- tls.certificate.yml
- ingress.yml
- pvc.yml

# Note: commonLabels removed to avoid selector immutability issues
# Labels are already defined in deployment.yml
