---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: decypharr-clusterlab-cc
  namespace: media-services
spec:
  secretName: decypharr-clusterlab-cc-tls
  dnsNames:
    - decypharr.clusterlab.cc
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
