---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: decypharr-clusterlab-cc
  namespace: media-services
spec:
  secretName: decypharr-clusterlab-cc-tls
  dnsNames:
    - decypharr.clusterlab.cc
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: radarr-dav-clusterlab-cc
  namespace: media-services
spec:
  secretName: radarr-dav-clusterlab-cc-tls
  dnsNames:
    - radarr-dav.clusterlab.cc
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarr-dav-clusterlab-cc
  namespace: media-services
spec:
  secretName: sonarr-dav-clusterlab-cc-tls
  dnsNames:
    - sonarr-dav.clusterlab.cc
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: streaming-clusterlab-cc
  namespace: media-services
spec:
  secretName: streaming-clusterlab-cc-tls
  dnsNames:
    - streaming.clusterlab.cc
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
