---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jackett
  namespace: default
  annotations:
    gethomepage.dev/href: "https://jackett.clusterlab.cc"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "AI-powered documentation assistant"
    gethomepage.dev/group: Tools
    gethomepage.dev/icon: jackett
    gethomepage.dev/name: jackett
    gethomepage.dev/pod-selector: "app=jackett"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`jackett.clusterlab.cc`)
      kind: Rule
      services:
        - name: jackett
          port: http
  tls:
    secretName: jackett-tls
