---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jackett-tls
  namespace: default
spec:
  secretName: jackett-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - jackett.clusterlab.cc
