---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: plex-clusterlab-cc
  namespace: media-services
spec:
  secretName: plex-clusterlab-cc-tls
  dnsNames:
    - plex.clusterlab.cc
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
