---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: explo-clusterlab-cc
  namespace: media-services
spec:
  secretName: explo-clusterlab-cc-tls
  dnsNames:
    - explo.clusterlab.cc
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
