---
apiVersion: v1
kind: Namespace
metadata:
  name: storage
---
apiVersion: v1
kind: Secret
metadata:
  name: samba-credentials
  namespace: storage
type: Opaque
stringData:
  username: samba
  password: "changeme"  # CHANGE THIS!
---
# Secret for use in other namespaces (media-services, etc.)
apiVersion: v1
kind: Secret
metadata:
  name: samba-credentials
  namespace: media-services
type: Opaque
stringData:
  username: samba
  password: "changeme"  # CHANGE THIS!
