apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyseerr
  namespace: media-services
  annotations:
    gethomepage.dev/href: "http://jellyseerr.clusterlab.cc"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Request management and media discovery tool."
    gethomepage.dev/group: Media
    gethomepage.dev/icon: jellyseerr.png
    gethomepage.dev/name: Jellyseerr
    gethomepage.dev/pod-selector: "app=jellyseerr"

spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`jellyseerr.clusterlab.cc`)
      kind: Rule
      services:
        - name: jellyseerr
          port: http
  tls:
    secretName: jellyseerr-clusterlab-cc-tls
