---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media-services

resources:
- deployment.yml
- service.yml

commonLabels:
  app: jellyseerr
  app.kubernetes.io/name: jellyseerr
  app.kubernetes.io/component: media-request-management
