---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexterm-data
  namespace: default
  labels:
    app: nexterm
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: samba-storage
  resources:
    requests:
      storage: 5Gi
