---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nexterm-tls
  namespace: default
spec:
  secretName: nexterm-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - nexterm.clusterlab.cc
