apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyfin
  namespace: media-services
  annotations:
    gethomepage.dev/href: "https://jellyfin.clusterlab.cc"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Media streaming server"
    gethomepage.dev/group: Media Streaming
    gethomepage.dev/icon: jellyfin.png
    gethomepage.dev/name: Jellyfin
    gethomepage.dev/pod-selector: "app=jellyfin"

    gethomepage.dev/widget.type: "jellyfin"
    gethomepage.dev/widget.url: "http://jellyfin"
    gethomepage.dev/widget.key: "4038821385854512bf6998ff948427da"
    gethomepage.dev/widget.enableBlocks: "true"
    gethomepage.dev/widget.enableNowPlaying: "true"
    gethomepage.dev/widget.enableUser: "true"
    gethomepage.dev/widget.enableMediaControl: "true"
    gethomepage.dev/widget.showEpisodeNumber: "true"
    gethomepage.dev/widget.expandOneStreamToTwoRows: "true"

spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`jellyfin.clusterlab.cc`) || Host(`watch.clusterlab.cc`)
      kind: Rule
      services:
        - name: jellyfin
          port: http
  tls:
    secretName: jellyfin-clusterlab-cc-tls
