apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyseerr-clusterlab-cc
  namespace: media-services
spec:
  secretName: jellyseerr-clusterlab-cc-tls
  dnsNames:
    - jellyseerr.clusterlab.cc
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
