---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: media-services
  labels:
    app: jellyfin
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: dlna
    port: 1900
    targetPort: dlna
    protocol: UDP
  - name: discovery
    port: 7359
    targetPort: discovery
    protocol: UDP
  selector:
    app: jellyfin
