---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    gethomepage.dev/href: "https://grafana.clusterlab.cc"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Grafana dashboard for cluster monitoring"
    gethomepage.dev/group: Monitoring
    gethomepage.dev/icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/grafana.png
    gethomepage.dev/name: Grafana
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=grafana"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`grafana.clusterlab.cc`)
      kind: Rule
      services:
        - name: kube-prometheus-stack-grafana
          port: 80
  tls:
    secretName: grafana-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus
  namespace: monitoring
  annotations:
    gethomepage.dev/href: "https://prometheus.clusterlab.cc"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Prometheus monitoring for cluster"
    gethomepage.dev/group: Monitoring
    gethomepage.dev/icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/prometheus.png
    gethomepage.dev/name: Prometheus
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=prometheus"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`prometheus.clusterlab.cc`)
      kind: Rule
      services:
        - name: kube-prometheus-stack-prometheus
          port: 9090
  tls:
    secretName: prometheus-tls
