---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
- tls.certificate.yml
- ingress.yml
- servicemonitor-sonarr.yml
- servicemonitor-radarr.yml
- servicemonitor-lidarr.yml
- servicemonitor-prowlarr.yml
- servicemonitor-qbittorrent.yml
- servicemonitor-sabnzbd.yml
- servicemonitor-flaresolverr.yml
- servicemonitor-jellyfin.yml
- servicemonitor-jellyseerr.yml
- servicemonitor-profilarr.yml
- servicemonitor-stash.yml
- servicemonitor-cloudcmd.yml
- servicemonitor-homepage.yml
- servicemonitor-sonobarr.yml
- servicemonitor-glance.yml
- servicemonitor-whisparr.yml

commonLabels:
  app.kubernetes.io/part-of: monitoring
  monitoring: prometheus
