---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flaresolverr
  namespace: media-services
  labels:
    app: flaresolverr
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: flaresolverr
  endpoints:
  - port: http
    path: /
    interval: 30s
    scrapeTimeout: 10s
