---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-clusterlab-cc
  namespace: monitoring
spec:
  secretName: grafana-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: grafana.clusterlab.cc
  dnsNames:
    - grafana.clusterlab.cc
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-clusterlab-cc
  namespace: monitoring
spec:
  secretName: prometheus-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: prometheus.clusterlab.cc
  dnsNames:
    - prometheus.clusterlab.cc
