---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media-services

resources:
- decypharr
- radarr-dav
- sonarr-dav
- lidarr-dav
- jellyfin-dav
- navidrome-dav
- fladder-dav
- plex-dav

patches:
- target:
    kind: Deployment
  patch: |-
    - op: add
      path: /spec/template/spec/nodeSelector
      value:
        kubernetes.io/hostname: k3s-agent-01
