---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media-services

resources:
- deployment.yml
- service.yml
- ingress.yml
- tls.certificate.yml

commonLabels:
  app: organizr
  app.kubernetes.io/name: organizr
  app.kubernetes.io/component: service-organizer
