apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: organizr-clusterlab-cc
  namespace: media-services
spec:
  secretName: organizr-clusterlab-cc-tls
  dnsNames:
    - organizr.clusterlab.cc
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
