---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: cloudcmd
  namespace: media-system
  annotations:
    gethomepage.dev/href: "https://cloudcmd.clusterlab.cc"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "File manager"
    gethomepage.dev/group: Utilities
    gethomepage.dev/icon: cloudcmd.png
    gethomepage.dev/name: CloudCmd
    gethomepage.dev/pod-selector: "app=cloudcmd"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ff.clusterlab.cc`) || Host(`cloudcmd.clusterlab.cc`)
      kind: Rule
      services:
        - name: cloudcmd
          port: 80
  tls:
    secretName: cloudcmd-tls
