---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pixelfin-data
  namespace: default
  labels:
    app: pixelfin
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: samba-storage
  resources:
    requests:
      storage: 20Gi
