---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pixelfin-tls
  namespace: default
spec:
  secretName: pixelfin-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - pixelfin.clusterlab.cc
