---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: olivetin
  namespace: default
  labels:
    app: olivetin
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: olivetin
  template:
    metadata:
      labels:
        app: olivetin
    spec:
      containers:
        - name: olivetin
          image: docker.io/jamesread/olivetin:latest
          ports:
            - name: http
              containerPort: 1337
              protocol: TCP
          volumeMounts:
            - name: olivetin-config
              mountPath: "/config"
              readOnly: true
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: olivetin-config
          configMap:
            name: olivetin-config
