---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tools
resources:
  - configmap.yml
  - deployment.yml
  - service.yml
  - tls.certificate.yml
  - ingress.yml
  - ssh-secret.yml
