---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: olivetin-tls
  namespace: default
spec:
  secretName: olivetin-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - olivetin.clusterlab.cc
