apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: lidarr
  namespace: media-services
  annotations:
    gethomepage.dev/href: "http://lidarr.clusterlab.cc"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Music collection manager for Usenet and BitTorrent users."
    gethomepage.dev/group: Media
    gethomepage.dev/icon: lidarr.png
    gethomepage.dev/name: Lidarr
    gethomepage.dev/pod-selector: "app=lidarr"

spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`lidarr.clusterlab.cc`)
      kind: Rule
      services:
        - name: lidarr
          port: http
  tls:
    secretName: lidarr-clusterlab-cc-tls
