apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: lidarr
  namespace: media-services
  annotations:
    gethomepage.dev/href: "https://lidarr.clusterlab.cc"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Music automation"
    gethomepage.dev/group: Media Automation
    gethomepage.dev/icon: lidarr.png
    gethomepage.dev/name: Lidarr
    gethomepage.dev/pod-selector: "app=lidarr"

    gethomepage.dev/widget.type: "lidarr"
    gethomepage.dev/widget.url: "http://lidarr"
    gethomepage.dev/widget.key: "cca173b3d8914e66b31f160ed72ee28c"

spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`lidarr.clusterlab.cc`)
      kind: Rule
      services:
        - name: lidarr
          port: http
  tls:
    secretName: lidarr-clusterlab-cc-tls
