---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media-services

resources:
- deployment.yml
- service.yml

commonLabels:
  app: lidarr
  app.kubernetes.io/name: lidarr
  app.kubernetes.io/component: music-management
