---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opengist-tls
  namespace: default
spec:
  secretName: opengist-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - opengist.clusterlab.cc
