---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rdtclient-clusterlab-cc
  namespace: media-services
spec:
  secretName: rdtclient-clusterlab-cc-tls
  dnsNames:
    - rdtclient.clusterlab.cc
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
