---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: searxng
  namespace: default
  annotations:
    gethomepage.dev/href: "https://searxng.clusterlab.cc"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Privacy-respecting metasearch engine"
    gethomepage.dev/group: Tools
    gethomepage.dev/icon: searxng.png
    gethomepage.dev/name: SearXNG
    gethomepage.dev/pod-selector: "app=searxng"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`searxng.clusterlab.cc`)
      kind: Rule
      services:
        - name: searxng-service
          port: 8080
  tls:
    secretName: searxng-tls
