---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: searxng-data
  namespace: default
  labels:
    app: searxng
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: samba-storage
  resources:
    requests:
      storage: 5Ti