---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: searxng-tls
  namespace: default
spec:
  secretName: searxng-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - searxng.clusterlab.cc
