---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: navidrome-clusterlab-cc
  namespace: media-services
spec:
  secretName: navidrome-clusterlab-cc-tls
  dnsNames:
    - navidrome.clusterlab.cc
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
