---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: papra
  namespace: default
  labels:
    app: papra
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: papra
  template:
    metadata:
      labels:
        app: papra
    spec:
      containers:
        - name: papra
          image: ghcr.io/papra-hq/papra:latest
          ports:
            - name: http
              containerPort: 1221
              protocol: TCP
          env:
            - name: APP_BASE_URL
              value: "https://papra.clusterlab.cc"
          volumeMounts:
            - name: papra-data
              mountPath: /app/app-data
      volumes:
        - name: papra-data
          persistentVolumeClaim:
            claimName: papra-data-samba
