---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: papra-tls
  namespace: default
spec:
  secretName: papra-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - papra.clusterlab.cc
