---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bentopdf
  namespace: default
  labels:
    app: bentopdf
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: bentopdf
  template:
    metadata:
      labels:
        app: bentopdf
    spec:
      containers:
        - name: bentopdf
          image: bentopdf/bentopdf:latest
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
