---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bentopdf-tls
  namespace: default
spec:
  secretName: bentopdf-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - bentopdf.clusterlab.cc
