---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: storyteller-tls
  namespace: default
spec:
  secretName: storyteller-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - storyteller.clusterlab.cc
