apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fladder-clusterlab-cc
  namespace: media-services
spec:
  secretName: fladder-clusterlab-cc-tls
  dnsNames:
    - fladder.clusterlab.cc
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
