---
apiVersion: v1
kind: Service
metadata:
  name: slskd
  namespace: media-services
  labels:
    app: slskd
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: https
    port: 5031
    targetPort: https
    protocol: TCP
  - name: p2p
    port: 50300
    targetPort: p2p
    protocol: TCP
  selector:
    app: slskd
