---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: slskd-clusterlab-cc
  namespace: media-services
spec:
  secretName: slskd-clusterlab-cc-tls
  dnsNames:
    - slskd.clusterlab.cc
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
