---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: streaming-clusterlab-cc
  namespace: media-services
spec:
  secretName: streaming-clusterlab-cc-tls
  dnsNames:
    - streaming.clusterlab.cc
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
