---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media-services

resources:
- configmap.yml
- deployment.yml
- service.yml
- tls.certificate.yml
- ingress.yml

commonLabels:
  app: glance
  app.kubernetes.io/name: glance
  app.kubernetes.io/component: dashboard
