apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: glance-clusterlab-cc
  namespace: media-services
spec:
  secretName: glance-clusterlab-cc-tls
  dnsNames:
    - glance.clusterlab.cc
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
