apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sonobarr
  namespace: media-services
  annotations:
    gethomepage.dev/href: "https://sonobarr.clusterlab.cc"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Music management"
    gethomepage.dev/group: Utilities
    gethomepage.dev/icon: https://icons.clusterlab.cc/sonobarr
    gethomepage.dev/name: Sonobarr
    gethomepage.dev/pod-selector: "app=sonobarr"

spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`sonobarr.clusterlab.cc`)
      kind: Rule
      services:
        - name: sonobarr
          port: http
  tls:
    secretName: sonobarr-clusterlab-cc-tls
