---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media-services

resources:
- secret.yml
- deployment.yml
- service.yml
- tls.certificate.yml
- ingress.yml

commonLabels:
  app: sonobarr
  app.kubernetes.io/name: sonobarr
  app.kubernetes.io/component: music-discovery
