---
apiVersion: v1
kind: Secret
metadata:
  name: sonobarr-secrets
  namespace: media-services
type: Opaque
stringData:
  # Lidarr API configuration
  lidarr_api_key: "cca173b3d8914e66b31f160ed72ee28c"
  
  # Optional: Last.fm API credentials
  last_fm_api_key: ""
  last_fm_api_secret: ""
  
  # Optional: YouTube API key
  youtube_api_key: ""
  
  # Optional: OpenAI API key
  openai_api_key: ""
  
  # Sonobarr admin password
  sonobarr_superadmin_password: "95782641"

  secret_key: 5e9341b7-4ea4-415d-8b09-a1aa0d622efd