apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sonarr
  namespace: media-services
  annotations:
    gethomepage.dev/href: "https://sonarr.clusterlab.cc"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "TV show automation"
    gethomepage.dev/group: Media Automation
    gethomepage.dev/icon: sonarr.png
    gethomepage.dev/name: Sonarr
    gethomepage.dev/pod-selector: "app=sonarr"

    gethomepage.dev/widget.type: "sonarr"
    gethomepage.dev/widget.url: "http://sonarr"
    gethomepage.dev/widget.key: "843aca18c51d4a2189214b962efa514e"

spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`sonarr.clusterlab.cc`)
      kind: Rule
      services:
        - name: sonarr
          port: http
  tls:
    secretName: sonarr-clusterlab-cc-tls
