---
apiVersion: v1
kind: Service
metadata:
  name: registry-browser
  namespace: default
  labels:
    app: registry-browser
spec:
  type: ClusterIP
  selector:
    app: registry-browser
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
