---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: registry
  namespace: default
  annotations:
    gethomepage.dev/href: "https://registry.clusterlab.cc"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Docker Registry"
    gethomepage.dev/group: Tools
    gethomepage.dev/icon: docker.png
    gethomepage.dev/name: Registry
    gethomepage.dev/pod-selector: "app=registry"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`registry.clusterlab.cc`)
      kind: Rule
      services:
        - name: registry-service
          port: http
  tls:
    secretName: registry-tls
