---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tools

resources:
- pvc.yml
- deployment.yml
- service.yml
- tls.certificate.yml
- ingress.yml
- browser-deployment.yml
- browser-service.yml
- browser-tls.certificate.yml
- browser-ingress.yml
