---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media-services

resources:
- secret.yml
- deployment.yml
- service.yml
- tls.certificate.yml
- ingress.yml

commonLabels:
  app: booklore
  app.kubernetes.io/name: booklore
  app.kubernetes.io/component: book-library
