---
apiVersion: v1
kind: Secret
metadata:
  name: booklore-db-credentials
  namespace: media-services
  labels:
    app: booklore
type: Opaque
stringData:
  username: booklore
  password: ChangeMe_BookLoreApp_2025!
  root-password: ChangeMe_MariaDBRoot_2025!
