---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkding-tls
  namespace: default
spec:
  secretName: linkding-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - linkding.clusterlab.cc
