apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: frames
  namespace: media-services
  annotations:
    gethomepage.dev/href: "https://frames.clusterlab.cc"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "AI-powered media management"
    gethomepage.dev/group: Media
    gethomepage.dev/icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/jellyfin.png
    gethomepage.dev/name: Frames
    gethomepage.dev/pod-selector: "app=frames"

spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`frames.clusterlab.cc`)
      kind: Rule
      services:
        - name: frames
          port: http
  tls:
    secretName: frames-clusterlab-cc-tls
