apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tautulli
  namespace: media-services
  annotations:
    gethomepage.dev/href: "http://tautulli.clusterlab.cc"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Monitoring and tracking tool for Plex Media Server."
    gethomepage.dev/group: Media
    gethomepage.dev/icon: tautulli.png
    gethomepage.dev/name: Tautulli
    gethomepage.dev/pod-selector: "app=tautulli"

    gethomepage.dev/widget.type: "tautulli"
    gethomepage.dev/widget.url: "https://tautulli.clusterlab.cc"
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_TAUTULLI_API_KEY}}"

spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`tautulli.clusterlab.cc`)
      kind: Rule
      services:
        - name: tautulli
          port: http
  tls:
    secretName: tautulli-clusterlab-cc-tls
