apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tautulli-clusterlab-cc
  namespace: media-services
spec:
  secretName: tautulli-clusterlab-cc-tls
  dnsNames:
    - tautulli.clusterlab.cc
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
