---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-data-samba
  namespace: default
  labels:
    app: audiobookshelf
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: samba-storage
  resources:
    requests:
      storage: 5Gi
