---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: audiobookshelf-tls
  namespace: default
spec:
  secretName: audiobookshelf-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - audiobookshelf.clusterlab.cc
