---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media-services

resources:
- deployment.yml
- service.yml

commonLabels:
  app: flaresolverr
  app.kubernetes.io/name: flaresolverr
  app.kubernetes.io/component: cloudflare-bypass
