apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: flaresolverr-clusterlab-cc
  namespace: media-services
spec:
  secretName: flaresolverr-clusterlab-cc-tls
  dnsNames:
    - flaresolverr.clusterlab.cc
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
