apiVersion: apps/v1
kind: Deployment
metadata:
  name: rclone
  labels:
    app: rclone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rclone
  template:
    metadata:
      labels:
        app: rclone
    spec:
      containers:
        - name: rclone
          image: rclone/rclone
          command: ["rcd", "--rc-addr=0.0.0.0:5572", "--rc-no-auth"]
          ports:
            - name: rcd
              containerPort: 5572
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config/rclone
              subPath: shared/rclone
            - name: data
              mountPath: /data
              subPath: media
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: rclone-config-pvc
        - name: data
          persistentVolumeClaim:
            claimName: rclone-data-pvc
