---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rclone-tls
  namespace: default
spec:
  secretName: rclone-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - rclone.clusterlab.cc
