apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: polaris
  namespace: media-services
  annotations:
    gethomepage.dev/href: "https://polaris.clusterlab.cc"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Self-hosted music streaming service"
    gethomepage.dev/group: Libraries
    gethomepage.dev/icon: https://icons.clusterlab.cc/polaris
    gethomepage.dev/name: Polaris
    gethomepage.dev/pod-selector: "app=polaris"

spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`polaris.clusterlab.cc`)
      kind: Rule
      services:
        - name: polaris
          port: http
  tls:
    secretName: polaris-clusterlab-cc-tls
