apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: polaris-clusterlab-cc
  namespace: media-services
spec:
  secretName: polaris-clusterlab-cc-tls
  dnsNames:
    - polaris.clusterlab.cc
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
