apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: miniflux
  namespace: media-services
  annotations:
    gethomepage.dev/href: "https://miniflux.clusterlab.cc"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Minimalist RSS feed reader"
    gethomepage.dev/group: Utilities
    gethomepage.dev/icon: https://icons.clusterlab.cc/miniflux/02d1ca
    gethomepage.dev/name: Miniflux
    gethomepage.dev/pod-selector: "app=miniflux"

    gethomepage.dev/widget.type: "miniflux"
    gethomepage.dev/widget.url: "http://miniflux"
    gethomepage.dev/widget.key: "d0cad09dee15ae420c759fb38b87a03f4080bc5837c9395133be05ba0a48b08f"

spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`miniflux.clusterlab.cc`) || Host(`feed.clusterlab.cc`)
      kind: Rule
      services:
        - name: miniflux
          port: http
  tls:
    secretName: miniflux-clusterlab-cc-tls
