---
apiVersion: v1
kind: Secret
metadata:
  name: miniflux-credentials
  namespace: media-services
  labels:
    app: miniflux
type: Opaque
stringData:
  admin-username: admin
  admin-password: ChangeMe_MinifluxAdmin_2025!
  postgres-password: ChangeMe_MinifluxDB_2025!
