apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: miniflux-clusterlab-cc
  namespace: media-services
spec:
  secretName: miniflux-clusterlab-cc-tls
  dnsNames:
    - miniflux.clusterlab.cc
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
