---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: media-services
  labels:
    app: homepage
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
    traefik: true
  
  settings.yaml: |
    title: Media Services Dashboard
    theme: dark
    background: 
      image: https://images.alphacoders.com/134/thumb-1920-1343748.png
      brightness: 75
    color: slate
    headerStyle: boxed
    layout:
      Media Streaming:
        style: row
        columns: 4
      Media Automation:
        style: row
        columns: 4
      Download Clients:
        style: row
        columns: 2
      Libraries:
        style: row
        columns: 2
      Utilities:
        style: row
        columns: 2
      Monitoring:
        style: row
        columns: 2
      Tools:
        style: row
        columns: 2
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: false
      showSearchSuggestions: true
      hideVisitURL: false
  
  bookmarks.yaml: |
    - Developer Resources:
        - Homepage Widget: 
            - abbr: HW
              href: https://gethomepage.dev/widgets/
        - GitHub:
            - abbr: GH
              href: https://github.com/
        - Kubernetes Docs:
            - abbr: K8s
              href: https://kubernetes.io/docs/
  
  services.yaml: |
    - Links: 
        - GitHub:
            icon: https://icons.clusterlab.cc/github
            href: https://github.com
            description: Code hosting platform
              
  widgets.yaml: |
    - logo:
        icon: https://icons.clusterlab.cc/kubernetes
    
    - greeting:
        text_size: xl
        text: "Homepage of Nix based k3s cluster"
    
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "Media Services Cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    
    - resources:
        backend: kubernetes
        expanded: true
        cpu: true
        memory: true
    
    - datetime:
        text_size: l
        format:
          dateStyle: long
          timeStyle: short
          hourCycle: h23
    
    - search:
        provider: custom
        url: https://searxng.clusterlab.cc/search?q=
        suggestionUrl: https://ac.ecosia.org/autocomplete?type=list&q= # Optional
        showSearchSuggestions: true # Optional
        target: _blank
  
  docker.yaml: ""
  
  custom.css: |
    body {
       font-family: "Google Sans";
       opacity: .8;
       }

    .border-theme-300, .border-theme-800 {
       border: 0;
       }

    .border-theme-800 {
       margin: 30px 45px 0 35px;
       }

    h2 {  
       margin-bottom: -10px;    
       }

    .text-left > .flex div .opacity-50 {
       color: #fff !important;
       }

    .items-start {
       padding-top: 0;
       }

    .h-15 {
       border-radius: 12px;
       margin: 10px 10px 10px 0;
       opacity: .75;
       backdrop-filter: blur(8px) !important;
       background: rgba(255,255,255,.15) !important;    
       }

    .text-left.cursor-pointer > .flex div:nth-child(2) {
       margin:5px 5px 5px 0;       
       padding-left: 0 !important;   
       }

    img {
       width: 38px; 
       height: 38px;
       margin: 10px;
       position: relative;
       left: 10px !important;
       }

    .px-2.flex-1 {
       margin-left: 15px;       
       }

    .rounded-l-md {
       padding: 10px !important;       
       }

    .grow .text-xl {
       margin-bottom: 10px;
    }
  
  custom.js: ""
