---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage-clusterlab-cc
  namespace: media-services
spec:
  secretName: homepage-clusterlab-cc-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: homepage.clusterlab.cc
  dnsNames:
    - homepage.clusterlab.cc
