---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: uptime-kuma
  namespace: default
  annotations:
    gethomepage.dev/href: "https://uptime.clusterlab.cc"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Uptime Monitoring"
    gethomepage.dev/group: Tools
    gethomepage.dev/icon: uptime-kuma.png
    gethomepage.dev/name: Uptime Kuma
    gethomepage.dev/pod-selector: "app=uptime-kuma"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`uptime.clusterlab.cc`)
      kind: Rule
      services:
        - name: uptime-kuma-service
          port: http
  tls:
    secretName: uptime-kuma-tls
