apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prowlarr
  namespace: media-services
  annotations:
    gethomepage.dev/href: "https://prowlarr.clusterlab.cc"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Indexer manager"
    gethomepage.dev/group: Media Automation
    gethomepage.dev/icon: prowlarr.png
    gethomepage.dev/name: Prowlarr
    gethomepage.dev/pod-selector: "app=prowlarr"

    gethomepage.dev/widget.type: "prowlarr"
    gethomepage.dev/widget.url: "http://prowlarr"
    gethomepage.dev/widget.key: "3989241f2c5e42b8b4d6f572202bf7f6"

spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`prowlarr.clusterlab.cc`)
      kind: Rule
      services:
        - name: prowlarr
          port: http
  tls:
    secretName: prowlarr-clusterlab-cc-tls
