---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media-services

resources:
- deployment.yml
- service.yml

commonLabels:
  app: prowlarr
  app.kubernetes.io/name: prowlarr
  app.kubernetes.io/component: indexer-manager
