apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prowlarr-clusterlab-cc
  namespace: media-services
spec:
  secretName: prowlarr-clusterlab-cc-tls
  dnsNames:
    - prowlarr.clusterlab.cc
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
