---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: automad
  namespace: default
  labels:
    app: automad
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: automad
  template:
    metadata:
      labels:
        app: automad
    spec:
      containers:
        - name: automad
          image: automad/automad:latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: automad-data
              mountPath: /app
              subPath: shared/automad
      volumes:
        - name: automad-data
          persistentVolumeClaim:
            claimName: automad-data-samba
