---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: automad-tls
  namespace: default
spec:
  secretName: automad-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - automad.clusterlab.cc
