---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dozzle
  namespace: default
spec:
  secretName: dozzle-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - dozzle.clusterlab.cc
