---
apiVersion: v1
kind: Service
metadata:
  name: pyload
  namespace: media-services
  labels:
    app: pyload
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: clicknload
    port: 9666
    targetPort: clicknload
    protocol: TCP
  selector:
    app: pyload
