---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pyload-clusterlab-cc
  namespace: media-services
spec:
  secretName: pyload-clusterlab-cc-tls
  dnsNames:
    - pyload.clusterlab.cc
    - injest.pyload.clusterlab.cc
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
