apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mediamanager-clusterlab-cc
  namespace: media-services
spec:
  secretName: mediamanager-clusterlab-cc-tls
  dnsNames:
    - mediamanager.clusterlab.cc
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
