apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whisparr
  namespace: media-services
  annotations:
    gethomepage.dev/href: "https://whisparr.clusterlab.cc"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Adult content automation"
    gethomepage.dev/group: Media Automation
    gethomepage.dev/icon: whisparr.png
    gethomepage.dev/name: Whisparr
    gethomepage.dev/pod-selector: "app=whisparr"

    gethomepage.dev/widget.type: "radarr"
    gethomepage.dev/widget.url: "http://whisparr"
    gethomepage.dev/widget.key: "70d8f379cecc4188860043dfe118b4ae"
    gethomepage.dev/widget.fields: '["wanted", "queued"]'

spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`whisparr.clusterlab.cc`)
      kind: Rule
      services:
        - name: whisparr
          port: http
  tls:
    secretName: whisparr-clusterlab-cc-tls
