apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whisparr
  namespace: media-services
  annotations:
    gethomepage.dev/href: "http://whisparr.clusterlab.cc"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Adult content collection manager for Usenet and BitTorrent users."
    gethomepage.dev/group: Media
    gethomepage.dev/icon: whisparr.png
    gethomepage.dev/name: Whisparr
    gethomepage.dev/pod-selector: "app=whisparr"

spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`whisparr.clusterlab.cc`)
      kind: Rule
      services:
        - name: whisparr
          port: http
  tls:
    secretName: whisparr-clusterlab-cc-tls
