---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media-services

resources:
- deployment.yml
- service.yml
- tls.certificate.yml
- ingress.yml

commonLabels:
  app: whisparr
  app.kubernetes.io/name: whisparr
  app.kubernetes.io/component: adult-content-management
