---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- pvc.yml
- secret.yml
- deployment.yml
- service.yml
- tls.certificate.yml
- ingress.yml

patches:
- target:
    kind: Deployment
    name: jellystat-db
  patch: |-
    - op: add
      path: /spec/template/spec/nodeSelector
      value:
        kubernetes.io/hostname: k3s-agent-01
- target:
    kind: Deployment
    name: jellystat
  patch: |-
    - op: add
      path: /spec/template/spec/nodeSelector
      value:
        kubernetes.io/hostname: k3s-agent-01
