---
apiVersion: v1
kind: Secret
metadata:
  name: jellystat-secret
  namespace: default
  labels:
    app: jellystat
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: mypassword
  JWT_SECRET: my-secret-jwt-key
