---
apiVersion: v1
kind: Service
metadata:
  name: jellystat-db-service
  namespace: default
  labels:
    app: jellystat
    component: database
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
  selector:
    app: jellystat
    component: database
---
apiVersion: v1
kind: Service
metadata:
  name: jellystat-service
  namespace: default
  labels:
    app: jellystat
    component: app
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: jellystat
    component: app
