---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellystat-tls
  namespace: default
spec:
  secretName: jellystat-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - jellystat.clusterlab.cc
