---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sonarr-dav
  namespace: media-services
  annotations:
    gethomepage.dev/href: "http://sonarr-dav.clusterlab.cc"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "TV series collection manager for WebDAV/Debrid users."
    gethomepage.dev/group: Media
    gethomepage.dev/icon: sonarr.png
    gethomepage.dev/name: Sonarr DAV
    gethomepage.dev/pod-selector: "app=sonarr-dav"

    gethomepage.dev/widget.type: "sonarr"
    gethomepage.dev/widget.url: "http://sonarr-dav"
    gethomepage.dev/widget.key: "b547703628be4f4094542759a95d62e6"

spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`sonarr-dav.clusterlab.cc`)
      kind: Rule
      services:
        - name: sonarr-dav
          port: http
  tls:
    secretName: sonarr-dav-clusterlab-cc-tls
