apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: radarr
  namespace: media-services
  annotations:
    gethomepage.dev/href: "http://radarr.clusterlab.cc"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Movie collection manager for Usenet and BitTorrent users."
    gethomepage.dev/group: Media
    gethomepage.dev/icon: radarr.png
    gethomepage.dev/name: Radarr
    gethomepage.dev/pod-selector: "app=radarr"

spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`radarr.clusterlab.cc`)
      kind: Rule
      services:
        - name: radarr
          port: http
  tls:
    secretName: radarr-clusterlab-cc-tls
