---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media-services

resources:
- deployment.yml
- service.yml

commonLabels:
  app: radarr
  app.kubernetes.io/name: radarr
  app.kubernetes.io/component: movie-management
