apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: radarr-clusterlab-cc
  namespace: media-services
spec:
  secretName: radarr-clusterlab-cc-tls
  dnsNames:
    - radarr.clusterlab.cc
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
