apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sabnzbd
  namespace: media-services
  annotations:
    gethomepage.dev/href: "http://sabnzbd.clusterlab.cc"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Free and easy binary newsreader."
    gethomepage.dev/group: Media
    gethomepage.dev/icon: sabnzbd.png
    gethomepage.dev/name: SABnzbd
    gethomepage.dev/pod-selector: "app=sabnzbd"

spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`sabnzbd.clusterlab.cc`)
      kind: Rule
      services:
        - name: sabnzbd
          port: http
  tls:
    secretName: sabnzbd-clusterlab-cc-tls
