---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfhst-icons-tls
  namespace: default
spec:
  secretName: selfhst-icons-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - icons.clusterlab.cc
