apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyswarm
  namespace: media-services
  annotations:
    gethomepage.dev/href: "http://jellyswarm.clusterlab.cc"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Jellyfin swarm management interface"
    gethomepage.dev/group: Media
    gethomepage.dev/icon: jellyfin.png
    gethomepage.dev/name: Jellyswarm
    gethomepage.dev/pod-selector: "app=jellyswarm"

spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`jellyswarm.clusterlab.cc`)
      kind: Rule
      services:
        - name: jellyswarm
          port: http
  tls:
    secretName: jellyswarm-clusterlab-cc-tls
