---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media-services

resources:
- deployment.yml
- service.yml
- ingress.yml
- tls.certificate.yml
- pvc.yml

commonLabels:
  app: jellyswarm
  app.kubernetes.io/name: jellyswarm
  app.kubernetes.io/component: jellyfin-management
