apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyswarm-clusterlab-cc
  namespace: media-services
spec:
  secretName: jellyswarm-clusterlab-cc-tls
  dnsNames:
    - jellyswarm.clusterlab.cc
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
