apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: qbittorrent
  namespace: media-services
  annotations:
    gethomepage.dev/href: "https://qbittorrent.clusterlab.cc"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Torrent client"
    gethomepage.dev/group: Download Clients
    gethomepage.dev/icon: qbittorrent.png
    gethomepage.dev/name: qBittorrent
    gethomepage.dev/pod-selector: "app=qbittorrent"

    gethomepage.dev/widget.type: "qbittorrent"
    gethomepage.dev/widget.url: "http://qbittorrent-bittorrent"
    gethomepage.dev/widget.username: "admin"
    gethomepage.dev/widget.password: "95782641"

spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`qbittorrent.clusterlab.cc`)
      kind: Rule
      services:
        - name: qbittorrent
          port: http
  tls:
    secretName: qbittorrent-clusterlab-cc-tls
