---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media-services

resources:
- deployment.yml
- service.yml

commonLabels:
  app: qbittorrent
  app.kubernetes.io/name: qbittorrent
  app.kubernetes.io/component: torrent-client
