---
apiVersion: v1
kind: Secret
metadata:
  name: youtarr-credentials
  namespace: media-services
  labels:
    app: youtarr
type: Opaque
stringData:
  db-root-password: 95782641
  admin-username: admin
  admin-password: 95782641
