apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: youtarr-clusterlab-cc
  namespace: media-services
spec:
  secretName: youtarr-clusterlab-cc-tls
  dnsNames:
    - youtarr.clusterlab.cc
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
